version: '3'

# TODO: change to a docker managed volume
services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres 
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data